#!/bin/bash

ticket=$(git branch --show-current | grep -oE "[A-Z]{3,6}-\d+")

if [[ $ticket ]]; then
  msg="$1 $ticket"
else
  echo 'cant detect ticket number'
  msg="$1 NOISSUE"
fi

echo $msg
git commit -m "$msg"
