# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# $filemanager = $HOME/.bin/kiorg
# $fileManager = $HOME/.bin/kiorg
$filemanager = nautilus
$terminal = kitty 
# $applauncher = rofi -show combi -modi window,run,combi,config:$HOME/.config/rofi/scripts/edit-config.sh -combi-modi run,window -terminal $terminal
$applauncher = rofi -show combi -modi window,drun,combi -combi-modi drun,window
$idlehandler = hypridle
$capturing = grim -g "$(slurp)" - | swappy -f -
$browser = helium-browser
$editor = code
$launch = ~/.config/hypr/scripts/app_launcher.sh
$player = ~/.config/hypr/scripts/player.sh
